title: "Buttons"
description: |
  Buttons should be used when an obvious action is required. Don't ever use the buttons, just to make it easier for the user to know the call-to-action on the screen.

patterns:
  basic:
    fields:
      - name: text
        type: string
        example: "See collection!"
      - name: url
        type: url
        example: "/products/"
    title: "Basic"
    description: |
      This is the basic button that should be used only use in front of a light background.
    width: "12em"
  ghost:
    fields:
      - name: text
        type: string
        example: "See collection!"
      - name: url
        type: url
        example: "/products/"
    title: "Ghost"
    description: |
      The ghost button is only to be placed when on top of a banner. So we can showcase the image of the banner through the button.
    background: "--color-secondary"
  light:
    fields:
      - name: text
        type: string
        example: "See collection!"
      - name: url
        type: url
        example: "/products/"
